/**
 * Generators for the Claude Code side of a fiefdom repo.
 *
 * Everything here is derived from `.fiefdom/fiefs.json` and regenerated by
 * `fiefdom sync`, so the config file stays the single source of truth shared
 * with the Pi extension.
 */

import type { FiefConfig, FiefdomConfig } from "../../core/config.ts";
import type { FiefMemory } from "../../core/memory.ts";
import { fiefInstructions, serfInstructions } from "../../core/persona.ts";
import { baronies, territories } from "../../core/config.ts";

export const VASSAL_PREFIX = "vassal-";
export const BARON_PREFIX = "baron-";
export const SERF_PREFIX = "serf-";
/** Older names, still recognised so existing sessions keep working. */
const LEGACY_PREFIXES = ["fief-", "wita-"];
export const AGENT_PREFIXES = [
	VASSAL_PREFIX,
	BARON_PREFIX,
	SERF_PREFIX,
	...LEGACY_PREFIXES,
];

/** Agent name Claude Code uses (`subagent_type`) for the holder of a fief. */
export function agentName(fief: { id: string; role?: string }): string {
	return `${fief.role === "baron" ? BARON_PREFIX : VASSAL_PREFIX}${fief.id}`;
}

/** The helper bound to that fief's land. */
export function serfName(fief: { id: string }): string {
	return `${SERF_PREFIX}${fief.id}`;
}

/** Inverse of `agentName`; returns null for agents that are not fiefdom's. */
export function fiefIdFromAgent(agentType: string | undefined | null): string | null {
	if (!agentType) return null;
	// Plugin-scoped names arrive as "plugin:agent"; take the last segment.
	const bare = agentType.split(":").pop()!;
	const prefix = AGENT_PREFIXES.find((p) => bare.startsWith(p));
	return prefix ? bare.slice(prefix.length) : null;
}

/**
 * A `.claude/agents/fief-<id>.md` definition.
 */
export function agentFile(
	fief: FiefConfig,
	config: FiefdomConfig,
	persona: string,
	memorySnapshot: string,
	bin: string
): string {
	const landless = fief.paths.length === 0;

	const description =
		fief.description?.trim() ||
		(landless
			? `${fief.id}: holds no land, so consult it for review and gaps rather than assigning work.`
			: `${fief.id} specialist. Holds ${fief.paths.join(", ")}. Use for any change on that land.`);

	const frontmatter = [
		"---",
		`name: ${agentName(fief)}`,
		`description: ${JSON.stringify(description)}`,
		"model: inherit",
		// A holder with no land cannot write anything, so withhold the tools too.
		...(landless ? ["disallowedTools: Write, Edit, MultiEdit, NotebookEdit"] : []),
		"---",
	].join("\n");

	return `${frontmatter}

<!-- Generated by fiefdom sync from ${config.paths.stateDirName}/fiefs.json. Edit the persona at ${fief.persona} instead; this file is overwritten. -->

${persona.trim()}

${fiefInstructions(fief, config, bin)}

## Prior learnings

${memorySnapshot}
`;
}

/**
 * A `.claude/agents/serf-<id>.md` definition: the helper a holder can put on a
 * narrow piece of its own work. Bound to the same land, keeps no memory, and
 * cannot delegate further — which is what keeps the tree two deep.
 */
export function serfFile(fief: FiefConfig, config: FiefdomConfig, persona: string): string {
	const frontmatter = [
		"---",
		`name: ${serfName(fief)}`,
		`description: ${JSON.stringify(
			`Helper bound to the ${fief.id} fief. Spawned by ${agentName(fief)} for one narrow task on its own land.`
		)}`,
		"model: inherit",
		// Serfs do not spawn serfs.
		"disallowedTools: Agent",
		"---",
	].join("\n");

	return `${frontmatter}

<!-- Generated by fiefdom sync from ${config.paths.stateDirName}/fiefs.json. Edit the persona at ${fief.persona} instead; this file is overwritten. -->

${persona.trim()}

${serfInstructions(fief, config)}
`;
}

/**
 * Context injected into the liege's session by the SessionStart hook.
 */
export function orchestratorContext(config: FiefdomConfig, bin: string): string {
	const table = territories(config)
		.map((f) => `- **${f.id}** — vassal \`${agentName(f)}\` holds ${f.paths.join(", ")}`)
		.join("\n");

	const scattered = baronies(config);
	const baronTable = scattered.length
		? `\n\nBaronies — holdings scattered through the fiefs above:\n` +
			scattered
				.map(
					(f) =>
						`- **${f.id}** — baron \`${agentName(f)}\` holds ${f.paths.join(", ") || "no land, so consult rather than assign"}`
				)
				.join("\n")
		: "";

	const enforcement =
		config.enforcement === "off"
			? "Boundaries are advisory in this repo (enforcement: off)."
			: config.enforcement === "orchestrator"
				? "A hook blocks *your* writes; fief agents are unchecked."
				: "A hook blocks your writes and any fief write outside its own paths.";

	return `# Fiefdom is active

This repository is divided into fiefs — areas of land. You are the **liege**:
the fiefs are held from you, you grant the work and receive the results, and
you do not work the land yourself. ${enforcement}

${table}${baronTable}

## How to route work

- Delegate with the Agent tool using \`subagent_type: "${agentName(territories(config)[0] ?? config.fiefs[0])}"\` (etc.).
  Continue an existing holder with SendMessage so it keeps its context instead
  of spawning a second one for the same land.
- A holder may put serfs (\`serf-<id>\`) on parts of its own work. That is its
  call, not yours — you grant the work, it decides how to split it.
- For planning, ask each affected fief what it would need *before* assigning
  work, then reconcile the contracts yourself and hand each fief a task that
  already names the agreed interface. \`/fiefdom-plan\` does this fan-out.
- Consult the barons while planning, not only at the end: their land lies
  inside everyone else's, so they see what a single vassal cannot, and a gap
  named before the work is cheaper than one found after it.
- Cross-fief requests are worth recording: \`${bin} log --from <fief> --to <fief> --message "..."\`.
- The guard covers the shell too: a \`sed -i\`, a heredoc or a \`>\` redirection
  into a file you do not own is denied the same way an Edit is.
- Land nobody holds is writable by nobody. That is usually worth surfacing to
  the user rather than routing around: an unownable file is a hint that the code
  sits on a blurry boundary. Widening a fief or adding to \`sharedPaths\` in
  ${config.paths.stateDirName}/fiefs.json is the fallback, not the first answer.
- Holders persist their learnings; \`${bin} memory show --fief <id>\` tells you what
  a fief already knows.

Run \`${bin} status\` for the current picture, or \`/fiefdom\`.`;
}

/** Slash commands written to `.claude/commands/`. */
export function commandFiles(bin: string, stateDirName: string): Map<string, string> {
	const files = new Map<string, string>();

	files.set(
		"fiefdom.md",
		`---
description: Show fiefdom status, fief ownership and routing rules
allowed-tools: Bash(${bin} status:*), Bash(${bin} memory show:*)
---

Run \`${bin} status\` and report:

- each fief, the paths it owns, and how many learnings it has accumulated
- any repository directories no fief owns
- the agent to use for each (\`vassal-<id>\`, or \`baron-<id>\` for a barony)
  and a one-line reminder
  that routing happens through the Agent tool / SendMessage, not by editing
  files yourself

Keep it short — a table plus one line of guidance.
`
	);

	files.set(
		"fiefdom-setup.md",
		`---
description: Analyze this repo and configure (or reconfigure) fiefs
allowed-tools: Bash(${bin} analyze:*), Bash(${bin} init:*), Bash(${bin} sync:*), Read, Write, Edit
---

Configure fiefdom for this repository.

1. Run \`${bin} analyze --json\` to get the proposed division. It reports
   directories, detected frameworks, file counts and a confidence level.
2. Present the proposal to the user as a short list: fief id, paths, file
   count, why. Say plainly where the analyzer is guessing.
3. Ask the user to confirm or adjust before writing anything. Their edits win.
4. Write the agreed division to \`${stateDirName}/fiefs.json\` (create the file
   if the analyzer's output needs changing; \`${bin} init\` writes the
   analyzer's proposal verbatim and is the fast path when they accept it).
5. Write or refine each persona at \`${stateDirName}/fiefs/<id>/AGENT.md\` — the
   persona is the fief's system prompt in both Claude Code and Pi, so make it
   about domain expertise and conventions, not about boundaries (fiefdom adds
   those).
6. Run \`${bin} sync\` to regenerate the agent definitions and hooks.
7. Tell the user to restart the session (or \`/reload\`) so the new agents and
   the SessionStart context are picked up.

Existing memory is never deleted by setup — reconfiguring is safe.
`
	);

	files.set(
		"fiefdom-plan.md",
		`---
description: Plan a change across fiefs before any of them writes code
argument-hint: what you want to build
allowed-tools: Bash(${bin} status:*), Bash(${bin} owner:*), Bash(${bin} memory show:*), Bash(${bin} log:*), Read, Grep, Glob, Agent
---

Plan this change across the fiefs: $ARGUMENTS

Do not let anyone write code yet. The point is to settle the contracts first,
so each fief can then work alone instead of discovering the interface halfway
through.

1. Work out which fiefs the change touches. \`${bin} status\` lists them and
   \`${bin} owner <path>\` resolves any specific file.
2. Ask each affected fief what it would need, marking the request clearly as a
   planning query: they should answer with what they would change, what they
   need from others (exact signatures, routes, payload shapes) and what they
   are unsure about — and change nothing.
3. Consult the barons now rather than later. They hold what earlier sessions
   learned about their concern, and a gap named before the work is far cheaper
   than one found after it.
4. Reconcile the answers yourself. Where two fiefs disagree about an interface,
   decide it — that is the orchestrator's job, and leaving it open guarantees
   rework. Record cross-fief agreements with
   \`${bin} log --from <fief> --to <fief> --message "..."\`.
5. Present the plan: the agreed contracts, then one task per fief in dependency
   order, each naming the interface it can rely on. Ask before executing.

If the plan turns out to need one fief to wait on another for most of its work,
say so — that usually means the change is really one piece of work sitting
across a boundary, which is worth knowing before you split it in two.
`
	);

	files.set(
		"fiefdom-review.md",
		`---
description: Review fief boundaries, activity and accumulated learnings
allowed-tools: Bash(${bin} review:*), Bash(${bin} status:*), Bash(${bin} memory show:*), Read
---

Run \`${bin} review\` and turn it into a short report:

- **Current fiefs** — paths, learning counts, and the most recent learnings
- **Ownership gaps** — paths no fief owns, plus anything in \`sharedPaths\`.
  Treat these as a signal about the repository rather than a config oversight:
  a file nobody can own usually serves several concerns at once. Say for each
  whether the honest fix is moving/splitting the code, giving it to an existing
  fief, or creating one — and only suggest \`sharedPaths\` when the decision
  genuinely has to wait.
- **Possible new fiefs** — where the repo has grown past its divisions
- **Drift** — fiefs whose recorded learnings suggest they keep reaching outside
  their own paths

Then propose concrete edits to \`${stateDirName}/fiefs.json\`. Do not apply them
without the user's go-ahead; when they agree, edit the config and run
\`${bin} sync\`.
`
	);

	return files;
}

/** The hook entries fiefdom owns in `.claude/settings.local.json`. */
export function hookEntries(bin: string): Record<string, unknown[]> {
	const [command, ...baseArgs] = bin.split(" ");
	return {
		PreToolUse: [
			{
				matcher: "Write|Edit|MultiEdit|NotebookEdit|Bash",
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "pre-tool-use"],
						statusMessage: "Checking fief boundaries...",
					},
				],
			},
		],
		PostToolUse: [
			{
				matcher: "Bash",
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "post-tool-use"],
					},
				],
			},
		],
		SessionStart: [
			{
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "session-start"],
					},
				],
			},
		],
	};
}

/** Render a fief's memory as a snapshot block for the generated agent file. */
export function memorySnapshot(memory: FiefMemory, bin: string, fiefId: string): string {
	const summary = memory.getContextSummary();
	return `${summary}

_Snapshot taken at generation time. Run \`${bin} memory show --fief ${fiefId}\` for the current set._`;
}
