/**
 * Generators for the Claude Code side of a fiefdom repo.
 *
 * Everything here is derived from `.fiefdom/fiefs.json` and regenerated by
 * `fiefdom sync`, so the config file stays the single source of truth shared
 * with the Pi extension.
 */

import type { FiefConfig, FiefdomConfig } from "../../core/config.ts";
import type { FiefMemory } from "../../core/memory.ts";
import { fiefInstructions } from "../../core/persona.ts";
import { territories, witan } from "../../core/config.ts";

export const FIEF_PREFIX = "fief-";
export const WITA_PREFIX = "wita-";
export const AGENT_PREFIXES = [FIEF_PREFIX, WITA_PREFIX];

/** Agent name Claude Code uses (`subagent_type`). */
export function agentName(fief: { id: string; role?: string }): string {
	return `${fief.role === "wita" ? WITA_PREFIX : FIEF_PREFIX}${fief.id}`;
}

/** Inverse of `agentName`; returns null for agents that are not fiefdom's. */
export function fiefIdFromAgent(agentType: string | undefined | null): string | null {
	if (!agentType) return null;
	// Plugin-scoped names arrive as "plugin:agent"; take the last segment.
	const bare = agentType.split(":").pop()!;
	const prefix = AGENT_PREFIXES.find((p) => bare.startsWith(p));
	return prefix ? bare.slice(prefix.length) : null;
}

/**
 * A `.claude/agents/fief-<id>.md` definition.
 */
export function agentFile(
	fief: FiefConfig,
	config: FiefdomConfig,
	persona: string,
	memorySnapshot: string,
	bin: string
): string {
	const isWita = fief.role === "wita";

	const description =
		fief.description?.trim() ||
		(isWita
			? `${fief.id} wita. Holds no files; consult for review and gaps in ${fief.id}.`
			: `${fief.id} specialist. Owns ${fief.paths.join(", ")}. Use for any change under those paths.`);

	const frontmatter = [
		"---",
		`name: ${agentName(fief)}`,
		`description: ${JSON.stringify(description)}`,
		"model: inherit",
		// Neither kind delegates further; a wita additionally never writes.
		isWita
			? "disallowedTools: Agent, Write, Edit, MultiEdit, NotebookEdit"
			: "disallowedTools: Agent",
		"---",
	].join("\n");

	return `${frontmatter}

<!-- Generated by fiefdom sync from ${config.paths.stateDirName}/fiefs.json. Edit the persona at ${fief.persona} instead; this file is overwritten. -->

${persona.trim()}

${fiefInstructions(fief, config, bin)}

## Prior learnings

${memorySnapshot}
`;
}

/**
 * Context injected into the orchestrator session by the SessionStart hook.
 */
export function orchestratorContext(config: FiefdomConfig, bin: string): string {
	const table = territories(config)
		.map((f) => `- **${f.id}** (agent \`${agentName(f)}\`) holds ${f.paths.join(", ")}`)
		.join("\n");

	const advisors = witan(config);
	const witaTable = advisors.length
		? `\n\nThe witan — no land, consulted rather than assigned:\n` +
			advisors
				.map(
					(f) =>
						`- **${f.id}** (agent \`${agentName(f)}\`): ${f.description ?? `${f.id} across the whole repository`}`
				)
				.join("\n")
		: "";

	const enforcement =
		config.enforcement === "off"
			? "Boundaries are advisory in this repo (enforcement: off)."
			: config.enforcement === "orchestrator"
				? "A hook blocks *your* writes; fief agents are unchecked."
				: "A hook blocks your writes and any fief write outside its own paths.";

	return `# Fiefdom is active

This repository is divided into fiefs. You are the **orchestrator**: you read,
plan and route, but you do not edit files. ${enforcement}

${table}${witaTable}

## How to route work

- Delegate with the Agent tool using \`subagent_type: "${agentName(territories(config)[0] ?? config.fiefs[0])}"\` (etc.).
  Continue an existing fief with SendMessage so it keeps its context instead of
  spawning a second one for the same territory.
- For planning, ask each affected fief what it would need *before* assigning
  work, then reconcile the contracts yourself and hand each fief a task that
  already names the agreed interface. \`/fiefdom-plan\` does this fan-out.
- Consult the witan while planning, not only at the end: they hold what earlier
  sessions learned about their concern, and a gap named before the work is
  cheaper than one found after it.
- Cross-fief requests are worth recording: \`${bin} log --from <fief> --to <fief> --message "..."\`.
- The guard covers the shell too: a \`sed -i\`, a heredoc or a \`>\` redirection
  into a file you do not own is denied the same way an Edit is.
- Paths no fief owns are writable by nobody. That is usually worth surfacing to
  the user rather than routing around: an unownable file is a hint that the code
  sits on a blurry boundary. Widening a fief or adding to \`sharedPaths\` in
  ${config.paths.stateDirName}/fiefs.json is the fallback, not the first answer.
- Fiefs persist their learnings; \`${bin} memory show --fief <id>\` tells you what
  a fief already knows.

Run \`${bin} status\` for the current picture, or \`/fiefdom\`.`;
}

/** Slash commands written to `.claude/commands/`. */
export function commandFiles(bin: string, stateDirName: string): Map<string, string> {
	const files = new Map<string, string>();

	files.set(
		"fiefdom.md",
		`---
description: Show fiefdom status, fief ownership and routing rules
allowed-tools: Bash(${bin} status:*), Bash(${bin} memory show:*)
---

Run \`${bin} status\` and report:

- each fief, the paths it owns, and how many learnings it has accumulated
- any repository directories no fief owns
- the agent name to use for each (\`fief-<id>\`, or \`wita-<id>\` for the witan)
  and a one-line reminder
  that routing happens through the Agent tool / SendMessage, not by editing
  files yourself

Keep it short — a table plus one line of guidance.
`
	);

	files.set(
		"fiefdom-setup.md",
		`---
description: Analyze this repo and configure (or reconfigure) fiefs
allowed-tools: Bash(${bin} analyze:*), Bash(${bin} init:*), Bash(${bin} sync:*), Read, Write, Edit
---

Configure fiefdom for this repository.

1. Run \`${bin} analyze --json\` to get the proposed division. It reports
   directories, detected frameworks, file counts and a confidence level.
2. Present the proposal to the user as a short list: fief id, paths, file
   count, why. Say plainly where the analyzer is guessing.
3. Ask the user to confirm or adjust before writing anything. Their edits win.
4. Write the agreed division to \`${stateDirName}/fiefs.json\` (create the file
   if the analyzer's output needs changing; \`${bin} init\` writes the
   analyzer's proposal verbatim and is the fast path when they accept it).
5. Write or refine each persona at \`${stateDirName}/fiefs/<id>/AGENT.md\` — the
   persona is the fief's system prompt in both Claude Code and Pi, so make it
   about domain expertise and conventions, not about boundaries (fiefdom adds
   those).
6. Run \`${bin} sync\` to regenerate the agent definitions and hooks.
7. Tell the user to restart the session (or \`/reload\`) so the new agents and
   the SessionStart context are picked up.

Existing memory is never deleted by setup — reconfiguring is safe.
`
	);

	files.set(
		"fiefdom-plan.md",
		`---
description: Plan a change across fiefs before any of them writes code
argument-hint: what you want to build
allowed-tools: Bash(${bin} status:*), Bash(${bin} owner:*), Bash(${bin} memory show:*), Bash(${bin} log:*), Read, Grep, Glob, Agent
---

Plan this change across the fiefs: $ARGUMENTS

Do not let anyone write code yet. The point is to settle the contracts first,
so each fief can then work alone instead of discovering the interface halfway
through.

1. Work out which fiefs the change touches. \`${bin} status\` lists them and
   \`${bin} owner <path>\` resolves any specific file.
2. Ask each affected fief what it would need, marking the request clearly as a
   planning query: they should answer with what they would change, what they
   need from others (exact signatures, routes, payload shapes) and what they
   are unsure about — and change nothing.
3. Consult the witan now rather than later. They hold what earlier sessions
   learned about their concern, and a gap named before the work is far cheaper
   than one found after it.
4. Reconcile the answers yourself. Where two fiefs disagree about an interface,
   decide it — that is the orchestrator's job, and leaving it open guarantees
   rework. Record cross-fief agreements with
   \`${bin} log --from <fief> --to <fief> --message "..."\`.
5. Present the plan: the agreed contracts, then one task per fief in dependency
   order, each naming the interface it can rely on. Ask before executing.

If the plan turns out to need one fief to wait on another for most of its work,
say so — that usually means the change is really one piece of work sitting
across a boundary, which is worth knowing before you split it in two.
`
	);

	files.set(
		"fiefdom-review.md",
		`---
description: Review fief boundaries, activity and accumulated learnings
allowed-tools: Bash(${bin} review:*), Bash(${bin} status:*), Bash(${bin} memory show:*), Read
---

Run \`${bin} review\` and turn it into a short report:

- **Current fiefs** — paths, learning counts, and the most recent learnings
- **Ownership gaps** — paths no fief owns, plus anything in \`sharedPaths\`.
  Treat these as a signal about the repository rather than a config oversight:
  a file nobody can own usually serves several concerns at once. Say for each
  whether the honest fix is moving/splitting the code, giving it to an existing
  fief, or creating one — and only suggest \`sharedPaths\` when the decision
  genuinely has to wait.
- **Possible new fiefs** — where the repo has grown past its divisions
- **Drift** — fiefs whose recorded learnings suggest they keep reaching outside
  their own paths

Then propose concrete edits to \`${stateDirName}/fiefs.json\`. Do not apply them
without the user's go-ahead; when they agree, edit the config and run
\`${bin} sync\`.
`
	);

	return files;
}

/** The hook entries fiefdom owns in `.claude/settings.local.json`. */
export function hookEntries(bin: string): Record<string, unknown[]> {
	const [command, ...baseArgs] = bin.split(" ");
	return {
		PreToolUse: [
			{
				matcher: "Write|Edit|MultiEdit|NotebookEdit|Bash",
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "pre-tool-use"],
						statusMessage: "Checking fief boundaries...",
					},
				],
			},
		],
		PostToolUse: [
			{
				matcher: "Bash",
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "post-tool-use"],
					},
				],
			},
		],
		SessionStart: [
			{
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "session-start"],
					},
				],
			},
		],
	};
}

/** Render a fief's memory as a snapshot block for the generated agent file. */
export function memorySnapshot(memory: FiefMemory, bin: string, fiefId: string): string {
	const summary = memory.getContextSummary();
	return `${summary}

_Snapshot taken at generation time. Run \`${bin} memory show --fief ${fiefId}\` for the current set._`;
}
