/**
 * Generators for the Claude Code side of a fiefdom repo.
 *
 * Everything here is derived from `.fiefdom/fiefs.json` and regenerated by
 * `fiefdom sync`, so the config file stays the single source of truth shared
 * with the Pi extension.
 */

import type { FiefConfig, FiefdomConfig } from "../../core/config.ts";
import type { FiefMemory } from "../../core/memory.ts";
import { fiefInstructions } from "../../core/persona.ts";

export const AGENT_PREFIX = "fief-";

/** Agent name Claude Code uses for a fief (`subagent_type`). */
export function agentName(fiefId: string): string {
	return `${AGENT_PREFIX}${fiefId}`;
}

/** Inverse of `agentName`; returns null for non-fief agents. */
export function fiefIdFromAgent(agentType: string | undefined | null): string | null {
	if (!agentType) return null;
	// Plugin-scoped names arrive as "plugin:agent"; take the last segment.
	const bare = agentType.split(":").pop()!;
	return bare.startsWith(AGENT_PREFIX) ? bare.slice(AGENT_PREFIX.length) : null;
}

/**
 * A `.claude/agents/fief-<id>.md` definition.
 */
export function agentFile(
	fief: FiefConfig,
	config: FiefdomConfig,
	persona: string,
	memorySnapshot: string,
	bin: string
): string {
	const description =
		fief.description?.trim() ||
		`${fief.id} specialist. Owns ${fief.paths.join(", ")}. Use for any change under those paths.`;

	const frontmatter = [
		"---",
		`name: ${agentName(fief.id)}`,
		`description: ${JSON.stringify(description)}`,
		"model: inherit",
		// A fief does its own work; it does not get to spawn more agents.
		"disallowedTools: Agent",
		...(config.useWorktrees ? ["isolation: worktree"] : []),
		"---",
	].join("\n");

	return `${frontmatter}

<!-- Generated by fiefdom sync from ${config.paths.stateDirName}/fiefs.json. Edit the persona at ${fief.persona} instead; this file is overwritten. -->

${persona.trim()}

${fiefInstructions(fief, config, bin)}

## Prior learnings

${memorySnapshot}
`;
}

/**
 * Context injected into the orchestrator session by the SessionStart hook.
 */
export function orchestratorContext(config: FiefdomConfig, bin: string): string {
	const table = config.fiefs
		.map((f) => `- **${f.id}** (agent \`${agentName(f.id)}\`) owns ${f.paths.join(", ")}`)
		.join("\n");

	const enforcement =
		config.enforcement === "off"
			? "Boundaries are advisory in this repo (enforcement: off)."
			: config.enforcement === "orchestrator"
				? "A hook blocks *your* writes; fief agents are unchecked."
				: "A hook blocks your writes and any fief write outside its own paths.";

	return `# Fiefdom is active

This repository is divided into fiefs. You are the **orchestrator**: you read,
plan and route, but you do not edit files. ${enforcement}

${table}

## How to route work

- Delegate with the Agent tool using \`subagent_type: "${agentName(config.fiefs[0].id)}"\` (etc.).
  Continue an existing fief with SendMessage so it keeps its context instead of
  spawning a second one for the same territory.
- For planning, ask each affected fief what it would need *before* assigning
  work, then reconcile the contracts yourself and hand each fief a task that
  already names the agreed interface.
- Cross-fief requests are worth recording: \`${bin} log --from <fief> --to <fief> --message "..."\`.
- The guard covers the shell too: a \`sed -i\`, a heredoc or a \`>\` redirection
  into a file you do not own is denied the same way an Edit is.
- Paths no fief owns are writable by nobody. That is usually worth surfacing to
  the user rather than routing around: an unownable file is a hint that the code
  sits on a blurry boundary. Widening a fief or adding to \`sharedPaths\` in
  ${config.paths.stateDirName}/fiefs.json is the fallback, not the first answer.
- Fiefs persist their learnings; \`${bin} memory show --fief <id>\` tells you what
  a fief already knows.

Run \`${bin} status\` for the current picture, or \`/fiefdom\`.`;
}

/** Slash commands written to `.claude/commands/`. */
export function commandFiles(bin: string, stateDirName: string): Map<string, string> {
	const files = new Map<string, string>();

	files.set(
		"fiefdom.md",
		`---
description: Show fiefdom status, fief ownership and routing rules
allowed-tools: Bash(${bin} status:*), Bash(${bin} memory show:*)
---

Run \`${bin} status\` and report:

- each fief, the paths it owns, and how many learnings it has accumulated
- any repository directories no fief owns
- the agent name to use for each fief (\`fief-<id>\`) and a one-line reminder
  that routing happens through the Agent tool / SendMessage, not by editing
  files yourself

Keep it short — a table plus one line of guidance.
`
	);

	files.set(
		"fiefdom-setup.md",
		`---
description: Analyze this repo and configure (or reconfigure) fiefs
allowed-tools: Bash(${bin} analyze:*), Bash(${bin} init:*), Bash(${bin} sync:*), Read, Write, Edit
---

Configure fiefdom for this repository.

1. Run \`${bin} analyze --json\` to get the proposed division. It reports
   directories, detected frameworks, file counts and a confidence level.
2. Present the proposal to the user as a short list: fief id, paths, file
   count, why. Say plainly where the analyzer is guessing.
3. Ask the user to confirm or adjust before writing anything. Their edits win.
4. Write the agreed division to \`${stateDirName}/fiefs.json\` (create the file
   if the analyzer's output needs changing; \`${bin} init\` writes the
   analyzer's proposal verbatim and is the fast path when they accept it).
5. Write or refine each persona at \`${stateDirName}/fiefs/<id>/AGENT.md\` — the
   persona is the fief's system prompt in both Claude Code and Pi, so make it
   about domain expertise and conventions, not about boundaries (fiefdom adds
   those).
6. Run \`${bin} sync\` to regenerate the agent definitions and hooks.
7. Tell the user to restart the session (or \`/reload\`) so the new agents and
   the SessionStart context are picked up.

Existing memory is never deleted by setup — reconfiguring is safe.
`
	);

	files.set(
		"fiefdom-review.md",
		`---
description: Review fief boundaries, activity and accumulated learnings
allowed-tools: Bash(${bin} review:*), Bash(${bin} status:*), Bash(${bin} memory show:*), Read
---

Run \`${bin} review\` and turn it into a short report:

- **Current fiefs** — paths, learning counts, and the most recent learnings
- **Ownership gaps** — paths no fief owns, plus anything in \`sharedPaths\`.
  Treat these as a signal about the repository rather than a config oversight:
  a file nobody can own usually serves several concerns at once. Say for each
  whether the honest fix is moving/splitting the code, giving it to an existing
  fief, or creating one — and only suggest \`sharedPaths\` when the decision
  genuinely has to wait.
- **Possible new fiefs** — where the repo has grown past its divisions
- **Drift** — fiefs whose recorded learnings suggest they keep reaching outside
  their own paths

Then propose concrete edits to \`${stateDirName}/fiefs.json\`. Do not apply them
without the user's go-ahead; when they agree, edit the config and run
\`${bin} sync\`.
`
	);

	return files;
}

/** The hook entries fiefdom owns in `.claude/settings.local.json`. */
export function hookEntries(bin: string): Record<string, unknown[]> {
	const [command, ...baseArgs] = bin.split(" ");
	return {
		PreToolUse: [
			{
				matcher: "Write|Edit|MultiEdit|NotebookEdit|Bash",
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "pre-tool-use"],
						statusMessage: "Checking fief boundaries...",
					},
				],
			},
		],
		SessionStart: [
			{
				hooks: [
					{
						type: "command",
						command,
						args: [...baseArgs, "hook", "session-start"],
					},
				],
			},
		],
	};
}

/** Render a fief's memory as a snapshot block for the generated agent file. */
export function memorySnapshot(memory: FiefMemory, bin: string, fiefId: string): string {
	const summary = memory.getContextSummary();
	return `${summary}

_Snapshot taken at generation time. Run \`${bin} memory show --fief ${fiefId}\` for the current set._`;
}
