/**
 * How generated files and personas should invoke the fiefdom CLI.
 *
 * The CLI is what fief agents use to read and write their own memory, in both
 * harnesses, so the invocation has to be resolvable from inside an agent's
 * shell — an absolute node invocation unless a `fiefdom` on PATH belongs to
 * this checkout.
 */

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

export const PACKAGE_ROOT = path.resolve(import.meta.dirname, "..");
export const ENTRY = path.join(PACKAGE_ROOT, "bin", "fiefdom.ts");

let cached: string | null = null;

/**
 * @param stateDir when given, a per-repo shim is written there and used, so
 *   generated prompts and hooks reference one short path instead of a full
 *   node invocation.
 */
export function resolveBin(stateDir?: string): string {
	if (cached) return cached;

	const override = process.env.FIEFDOM_BIN;
	if (override) return (cached = override);

	try {
		const found = execFileSync("sh", ["-c", "command -v fiefdom"], {
			encoding: "utf-8",
		}).trim();
		if (found && fs.realpathSync(found).startsWith(PACKAGE_ROOT)) {
			return (cached = "fiefdom");
		}
	} catch {
		// Not on PATH; fall through.
	}

	if (stateDir) {
		try {
			return (cached = ensureShim(stateDir));
		} catch {
			// Could not write the shim (read-only checkout?); use node directly.
		}
	}

	return (cached = nodeInvocation());
}

export function nodeInvocation(): string {
	return `node --no-warnings --experimental-strip-types ${ENTRY}`;
}

/**
 * Write `<stateDir>/bin/fiefdom`, a one-line shim onto this checkout. Keeps
 * generated agent prompts readable and hook entries to a single command.
 */
export function ensureShim(stateDir: string): string {
	const shimPath = path.join(stateDir, "bin", "fiefdom");
	const contents = `#!/bin/sh
# Generated by fiefdom. Points at the checkout that created it.
exec ${nodeInvocation().replace(ENTRY, `"${ENTRY}"`)} "$@"
`;

	fs.mkdirSync(path.dirname(shimPath), { recursive: true });
	if (!fs.existsSync(shimPath) || fs.readFileSync(shimPath, "utf-8") !== contents) {
		fs.writeFileSync(shimPath, contents, "utf-8");
	}
	fs.chmodSync(shimPath, 0o755);
	return shimPath;
}
